# Generated by Django 5.2 on 2025-07-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_startuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='timezone',
            new_name='userTimezone',
        ),
    ]
