# Generated by Django 5.2 on 2025-07-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_timezone_customuser_usertimezone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('manage_regular_users', 'Can manage non-admin users')]},
        ),
    ]
