# Generated by Django 5.2 on 2025-06-15 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activity_unique_activity_name_per_user_and_more'),
        ('timeSections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to='activities.activity'),
        ),
    ]
