# Generated by Django 5.2 on 2025-06-21 20:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeSections', '0002_alter_stamp_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
