# Generated by Django 5.2 on 2025-06-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeSections', '0003_alter_stamp_id'),
    ]

    operations = [
    ]
