# Generated by Django 5.2 on 2025-07-01 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activity_unique_activity_name_per_user_and_more'),
        ('timeSections', '0005_empty_stamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stamp',
            index=models.Index(fields=['user', 'timestamp'], name='timeSection_user_id_ba4a00_idx'),
        ),
    ]
