# Generated by Django 5.2 on 2025-05-04 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_options_alter_activity_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activity',
            name='unique_activity_name_per_user',
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(condition=models.Q(('name__iexact', models.F('name'))), fields=('user', 'name'), name='unique_activity_name_per_user'),
        ),
    ]
