# Generated by Django 5.2 on 2025-06-27 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activity_unique_activity_name_per_user_and_more'),
        ('days', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('points', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='activities.activity')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_scores', to='days.day')),
            ],
            options={
                'ordering': ['-points'],
                'abstract': False,
                'unique_together': {('day', 'activity')},
            },
        ),
    ]
