# Generated by Django 5.2 on 2025-07-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0002_activityscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityscore',
            name='color',
        ),
        migrations.RemoveField(
            model_name='activityscore',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='activityscore',
            name='name',
        ),
    ]
